version: '3.9'
services:
  dev:
    container_name: app-dev
    image: app-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb

  prod:
    container_name: app-prod
    image: app-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: app-mongodb
    volumes:
      - ./db:/data/db
    networks:
      - app-network
    ports:
      - 27017:27017
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
